import{a as d,i as l,S as p}from"./assets/vendor-DU6yh4ar.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function m(a){return d.get("https://pixabay.com/api/",{params:{key:"49328511-2c3ca610241153d1ac84b83e7",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(i=>i.data.hits.length===0?(l.info({title:"No results!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),null):i.data.hits).catch(i=>{console.error("Error:",i)})}function h(a,r){a.innerHTML="";const o=r.map(({webformatURL:i,largeImageURL:e,tags:t,likes:s,views:c,comments:u,downloads:f})=>`<li class="gallery-item">
          <a href="${e}" class="gallery-item-link">
            <img class="gallery-item-img" src="${i}" alt="${t}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b>${s}</p>
            <p><b>Views:</b>${c}</p>
            <p><b>Comments:</b>${u}</p>
            <p><b>Downloads:</b>${f}</p>
          </div>
        </li>`).join("");a.insertAdjacentHTML("beforeend",o)}const n={form:document.querySelector(".form"),input:document.querySelector('[name="search-text"]'),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};let y=new p(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});n.form.addEventListener("submit",a=>{a.preventDefault();const r=n.input.value.trim();if(r===""){l.error({title:"Error:",message:"Please fill in the search field before submitting!",position:"topRight"});return}n.loader.hidden=!1,m(r).then(o=>{o&&(h(n.gallery,o),y.refresh())}).catch(o=>{console.error("Error:",o)}).finally(()=>{n.loader.hidden=!0}),n.form.reset()});
//# sourceMappingURL=index.js.map
